### ISSUE TITLE
peta_gender.pth

### ISSUE THREAD

**Issue by arionulibasa** [Umang1815/Age_and_Gender_Detection_through_CCTV_Videos#2]
Where is peta_gender.pth? I didn't find it

**Comment by seymasalih** [comment]
yes im in the same issue. i could not find it. Are we have to create this ?

**Comment by Umang1815** [comment]
Hey,
We have updated the Readme file. All the weights are accessible [here.](https://drive.google.com/drive/folders/1je0qOl4zY2aJoPHACK2CpqQXzEoWHSfl?usp=sharing)
